import type { PolicyVault, Agent, Transaction, Merchant, MerchantAPI, Payout } from '@/types';

export const mockVaults: PolicyVault[] = [
  {
    id: '1',
    name: 'Research Bot Budget',
    description: 'Daily budget for AI research operations',
    token: 'USDC',
    balance: 2450.00,
    dailyLimit: 100.00,
    maxPerTx: 5.00,
    status: 'active',
    createdAt: '2024-01-15',
    todaySpend: 45.23,
    totalCalls: 892,
    allowedMerchantsOnly: true,
    allowedAgentsOnly: true,
  },
  {
    id: '2',
    name: 'API Testing',
    description: 'Test budget for development',
    token: 'USDC',
    balance: 500.00,
    dailyLimit: 50.00,
    maxPerTx: 2.00,
    status: 'active',
    createdAt: '2024-02-01',
    todaySpend: 12.50,
    totalCalls: 156,
    allowedMerchantsOnly: false,
    allowedAgentsOnly: false,
  },
  {
    id: '3',
    name: 'Production Agent',
    description: 'Main production spending vault',
    token: 'USDT',
    balance: 10000.00,
    dailyLimit: 500.00,
    maxPerTx: 25.00,
    status: 'paused',
    createdAt: '2024-01-20',
    todaySpend: 0,
    totalCalls: 2341,
    allowedMerchantsOnly: true,
    allowedAgentsOnly: true,
  },
];

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'ResearchBot Alpha',
    description: 'Primary research and data gathering agent',
    apiKey: 'ss_agent_7f8a9b...3c4d',
    linkedVaults: ['1', '2'],
    status: 'active',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'DataSync Worker',
    description: 'Automated data synchronization tasks',
    apiKey: 'ss_agent_2e1d4c...8f9a',
    linkedVaults: ['1'],
    status: 'active',
    createdAt: '2024-02-10',
  },
  {
    id: '3',
    name: 'Legacy Agent',
    description: 'Deprecated agent for old workflows',
    apiKey: 'ss_agent_5a6b7c...1d2e',
    linkedVaults: [],
    status: 'revoked',
    createdAt: '2023-12-01',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    vaultId: '1',
    vaultName: 'Research Bot Budget',
    merchantId: 'm1',
    merchantName: 'OpenAI API',
    merchantLogo: '/placeholder.svg',
    agentId: '1',
    agentName: 'ResearchBot Alpha',
    amount: 0.0023,
    token: 'USDC',
    status: 'succeeded',
    timestamp: '2024-02-15T14:32:00Z',
    txHash: '0x7f8a...3c4d',
    x402PaymentId: 'x402_pay_abc123',
  },
  {
    id: '2',
    vaultId: '1',
    vaultName: 'Research Bot Budget',
    merchantId: 'm2',
    merchantName: 'Perplexity',
    agentId: '1',
    agentName: 'ResearchBot Alpha',
    amount: 0.0015,
    token: 'USDC',
    status: 'succeeded',
    timestamp: '2024-02-15T14:28:00Z',
    txHash: '0x2e1d...8f9a',
  },
  {
    id: '3',
    vaultId: '2',
    vaultName: 'API Testing',
    merchantId: 'm3',
    merchantName: 'Anthropic Claude',
    agentId: '2',
    agentName: 'DataSync Worker',
    amount: 0.0045,
    token: 'USDC',
    status: 'pending',
    timestamp: '2024-02-15T14:25:00Z',
  },
  {
    id: '4',
    vaultId: '1',
    vaultName: 'Research Bot Budget',
    merchantId: 'm1',
    merchantName: 'OpenAI API',
    agentId: '1',
    agentName: 'ResearchBot Alpha',
    amount: 0.0018,
    token: 'USDC',
    status: 'failed',
    timestamp: '2024-02-15T14:20:00Z',
  },
];

export const mockMerchants: Merchant[] = [
  { id: 'm1', name: 'OpenAI API', category: 'AI/ML', trusted: true, allowed: true },
  { id: 'm2', name: 'Perplexity', category: 'Search', trusted: true, allowed: true },
  { id: 'm3', name: 'Anthropic Claude', category: 'AI/ML', trusted: true, allowed: false },
  { id: 'm4', name: 'Cohere', category: 'AI/ML', trusted: false, allowed: false },
  { id: 'm5', name: 'Stability AI', category: 'Image Gen', trusted: true, allowed: true },
];

export const mockMerchantAPIs: MerchantAPI[] = [
  {
    id: 'api1',
    name: 'GPT-4 Completion API',
    baseUrl: 'https://api.yourservice.com',
    endpointPath: '/v1/completions',
    pricePerCall: 0.0023,
    token: 'USDC',
    chain: 'polygon',
    status: 'active',
    totalCalls: 15234,
    totalRevenue: 35.04,
  },
  {
    id: 'api2',
    name: 'Image Analysis',
    baseUrl: 'https://api.yourservice.com',
    endpointPath: '/v1/analyze',
    pricePerCall: 0.0050,
    token: 'USDC',
    chain: 'polygon',
    status: 'active',
    totalCalls: 8921,
    totalRevenue: 44.61,
  },
];

export const mockPayouts: Payout[] = [
  {
    id: 'p1',
    amount: 250.00,
    token: 'USDC',
    txHash: '0xabc123...def456',
    status: 'completed',
    timestamp: '2024-02-10T10:00:00Z',
  },
  {
    id: 'p2',
    amount: 180.50,
    token: 'USDC',
    txHash: '0x789ghi...012jkl',
    status: 'completed',
    timestamp: '2024-02-01T10:00:00Z',
  },
];

export const mockSpendData = [
  { date: 'Mon', spend: 45, limit: 100 },
  { date: 'Tue', spend: 78, limit: 100 },
  { date: 'Wed', spend: 92, limit: 100 },
  { date: 'Thu', spend: 55, limit: 100 },
  { date: 'Fri', spend: 83, limit: 100 },
  { date: 'Sat', spend: 34, limit: 100 },
  { date: 'Sun', spend: 67, limit: 100 },
];

export const mockTopMerchants = [
  { name: 'OpenAI API', category: 'AI/ML', spend7d: 145.23, calls: 892 },
  { name: 'Perplexity', category: 'Search', spend7d: 89.45, calls: 456 },
  { name: 'Anthropic Claude', category: 'AI/ML', spend7d: 67.80, calls: 321 },
  { name: 'Stability AI', category: 'Image Gen', spend7d: 34.12, calls: 178 },
];
